openapi: 3.0.0
# x-direktiv-api: gateway/v1

info:
  title: MyAPI
  description: the description of the API
  version: "1.0"

paths:
  /user:
    $ref: ./route1.yaml
  /user2:
    $ref: routes/route2.yaml

servers:
  - url: http://api.example.com/v1

components:
  schemas:
    OtherUser:
      $ref: ./components.yaml
