x-direktiv-api: gateway/v1

openapi: 3.0.0
info:
    description: the description of the API
    title: MyAPI
    version: "1.0"

paths:
    /testme:
        $ref: route1.yaml

components:
    securitySchemes:
        defaultApiKey:
            description: API key provided in console
            type: apiKey
            name: api-key
            in: header
        defaultApiKey2:
            description: API2 key provided in console
            type: apiKey
            name: api-key2
            in: header
    schemas:
        Date:
            format: date
            type: string
        OtherUser:
            $ref: components.yaml