components:
    schemas:
        Date:
            format: date
            type: string
        OtherUser:
            $ref: ../../components.yaml
info:
    contact:
        name: Jens
    description: the description of the API
    title: MyAPI
    version: "1.0"
openapi: 3.0.0
paths:
    /testme:
        $ref: ../../route1.yaml
x-direktiv-api: gateway/v1